'use strict';class Searcher{constructor(a,c,b,e){this.width=a;this.height=c;this.zoom=b;this.scales=e;this.index=-1;this.node=null}update(a,c,b,e){this.width=a;this.height=c;this.zoom=b;this.scales=e;this.node=null}search(a){this._unselectPrevious();let c=0;a&&""!=a&&(this.index=-1,this.d3Nodes=d3.selectAll("svg g .node").filter(b=>b.data.node_name.includes(a)),this.d3Nodes=this.d3Nodes.sort(function(b,e){return b.data.node_name.length-e.data.node_name.length}),c=this.d3Nodes.size());return c}searchNext(a){let c=
Math.min(this.d3Nodes.size()-1,this.index+1),b=this._getNode(c);b.node()&&(this._highlightNode(b),a&&this.centerOnNode(),this.index=c);return this.index+1}searchPrev(a){let c=Math.max(0,this.index-1),b=this._getNode(c);b.node()&&(this._highlightNode(b),a&&this.centerOnNode(),this.index=c);return this.index+1}centerOnNode(){var a=this.node;let c=d3.select("svg");var b=d3.zoomTransform(c.node());c.call(this.zoom.scaleBy,1/b.k);var e=0,d=0;a.node().transform.baseVal.consolidate()&&(d=a.node().transform.baseVal.consolidate().matrix,
e=d.e,d=d.f);b=d3.zoomTransform(c.node());a=-b.x;b=-b.y;e=this.width()/2-e+a;d=this.height()/2-d+b;c.transition().duration(250).call(this.zoom.translateBy,e,d)}_getNode(a){return d3.select(this.d3Nodes.nodes()[a])}_unselectPrevious(){this.node&&this.node.select("circle").style("fill",this.scales.colour).attr("r",this.scales.circle)}_highlightNode(a){this._unselectPrevious();a.select("circle").style("fill","rgb(254, 254, 81)").attr("r",c=>Math.min(3*this.scales.circle(c),30));a.raise();this.node=a}}
let treeVisHelpers={isNonIndexable:a=>a.data.hasOwnProperty("nonIndexableReason"),isLeaf:a=>null==a._children,setPlaceholder:function(a){if(a){d3.select("body svg").style("display","none");let c=document.getElementById("placeholder");c.innerHTML=a;c.style.display="block"}},clearPlaceholder:function(){d3.select("body svg").style("display","block");document.getElementById("placeholder").style.display="none"},chartSave:function(a){a=(new XMLSerializer).serializeToString(d3.select("svg").node());let c=
'\x3cdefs\x3e\x3cstyle type\x3d"text/css"\x3e\x3c![CDATA[\n'+cssHelpers.getCssRules()+"]]\x3e\x3c/style\x3e\x3c/defs\x3e",b=a.indexOf("\x3e")+1;a=a.substr(0,b)+"\n"+c+a.substr(b);java.jsToJavaSaveSvg(a)},showProgress:function(){d3.select("body svg").style("display","none");d3.select("#progressbar").style("display","block");this.updateProgress(0)},updateProgress:function(a){document.getElementById("progressbar").style.width=a+"%"},hideProgress:function(){d3.select("body svg").style("display","block");
d3.select("#progressbar").style("display","none");this.updateProgress(0)}};
function spiderUrltoolTipHtml(a){return"\x3cli\x3e\x3cbr/\x3e\x3c/li\x3e"+getTooltipLine(a.data.page_title,"visualisations.page_title.label")+(treeVisHelpers.isNonIndexable(a)?getTooltipLine(a.data.nonIndexableReason,"indexability.non_indexable"):"")+getTooltipLine(a.data.response_code,"visualisations.response_code.label")+getTooltipLine(a.data.h1,"visualisations.h1.label")+getTooltipLine(a.data.h2,"visualisations.h2.label")+getTooltipLine(a.data.crawl_depth,"table.column.crawl_depth")+getTooltipLine(a.data.unique_inlinks,
"table.column.unique_inlinks")+getTooltipLine(a.data.unique_outlinks,"table.column.unique_outlinks")+getTooltipLine(a.data.followed_outlinks,"visualisations.followed_outlinks.label")+getTooltipLine(a.data.percent_of_total,"table.column.percent_of_total")+getTooltipLine(a.data.word_count,"table.column.word_count")+getTooltipLine(a.data.ga_sessions,"visualisations.ga_sessions.label")+getTooltipLine(a.data.ga4_sessions,"visualisations.ga4_sessions.label")+getTooltipLine(a.data.gsc_clicks,"visualisations.gsc_clicks.label")+
getTooltipLine(a.data.gsc_impressions,"visualisations.gsc_impressions.label")+getTooltipLine(a.data.ahrefs_url_rating,"visualisations.ahrefs_url_rating.label")+getTooltipLine(a.data.moz_page_authority,"visualisations.moz_page_authority.label")+getTooltipLine(a.data.link_score,"visualisations.link_score.label")+getTooltipLine(a.data.structured_data_error_count,"visualisations.structured_data_error_count.label")+getTooltipLine(a.data.structured_data_total_types,"visualisations.structured_data_total_types.label")+
getTooltipLine(a.data.pagespeed_score,"visualisations.pagespeed_score.label")}function getTooltipLine(a,c){return null===a||void 0===a?"":"\x3cli\x3e\x3cstrong\x3e"+jsToJavaGetKey(c)+": \x3c/strong\x3e "+a+"\x3c/li\x3e"}function jsToJavaGetKey(a){return"undefined"===typeof java?translation_keys[a]:java.jsToJavaGetKey(a)}function focusHereMenuItem(a){return{title:jsToJavaGetKey("visualisations.context_menu.focus_here"),action:function(c,b,e){java.jsToJavaNodeFocus(a(b))}}}
function copyMenuItem(a){return{title:jsToJavaGetKey("visualisations.context_menu.copy"),action:function(c,b,e){void 0===window.java?(c=a(b),b=document.createElement("textarea"),document.body.appendChild(b),b.value=c,b.select(),document.execCommand("copy"),document.body.removeChild(b)):java.jsToJavaNodeCopy(a(b))}}}
function openInBrowserMenuItem(a){return{title:jsToJavaGetKey("visualisations.context_menu.open_in_browser"),action:function(c,b,e){void 0===window.java?window.open(a(b)):java.jsToJavaOpenInBrowser(a(b))}}}function getRightClickMenuArray(a){a=[focusHereMenuItem(a),copyMenuItem(a),openInBrowserMenuItem(a)];void 0===window.java&&a.shift();return a}
function formatNodeLabel(a,c){if(a.depth>c.textDisplayDepth-1)return"";a=(a||"").toString().trim();return 32<a.length?a.slice(0,29)+"...":a}
function CrawlMapStrategy(a){function c(d){return d.data.encoded_url}let b={lastUrlPathComponent:d=>{(d=d.data.display_url)&&"/"!==d?(d=d.split("/"),d=d.pop()||d.pop()):d="/";return d},page_title:d=>d.data.page_title,h1:d=>d.data.h1,h2:d=>d.data.h2},e=b.lastUrlPathComponent;return{setNodeLabel:function(d){e=b[d]},textGetter:function(d){return formatNodeLabel(e(d),a)},toolTipHtml:function(d){return"\x3cdiv class\x3d'tooltip'\x3e\x3cul\x3e\x3cli\x3e\x3cstrong\x3e"+jsToJavaGetKey("visualisations.url.label")+
": \x3c/strong\x3e "+d.data.display_url+"\x3c/li\x3e"+spiderUrltoolTipHtml(d)+"\x3c/ul\x3e\x3cdiv\x3e"},focussedNodeName:c,rightClickMenu:function(){return getRightClickMenuArray(c)}}}
function DirectoryStrategy(a){function c(b){let e=[];for(;b;){let d=b.data.node_name;0==e.length||d.endsWith("/")||(d+="/");e.push(d);b=b.parent}e.reverse();e.shift();return e.join("").replace(/(http[s]?)/,"$1:/")}return{setNodeLabel:function(b){},textGetter:function(b){return formatNodeLabel(b.data.node_name,a)},toolTipHtml:function(b){let e="\x3cdiv class\x3d'tooltip'\x3e\x3cul\x3e\x3cli\x3e\x3cstrong\x3e"+jsToJavaGetKey("visualisations.tree_path.label")+": \x3c/strong\x3e"+c(b)+"\x3c/li\x3e";
b.data.display_url&&(e+=spiderUrltoolTipHtml(b));return e+"\x3c/ul\x3e\x3cdiv\x3e"},focussedNodeName:c,rightClickMenu:function(){return getRightClickMenuArray(c)}}}function strategyFactory(a,c){let b;"DIRECTORY"===c?b=DirectoryStrategy(a):"CRAWL_MAP"===c&&(b=CrawlMapStrategy(a));return b};
