'use strict';function treeChart(){function c(a){a.each(function(d){x=d3.select(this).select("body").select("svg").attr("width",r).attr("height",l);u=x.select("g");y=d3.zoom().scaleExtent([.01,10]).on("zoom",()=>u.attr("transform",d3.event.transform));x.call(y);f||x.call(y.translateBy,100,l/2);A=d3.tree().nodeSize([b.nodeSpacing,b.nodeSpacing]);g=d3.hierarchy(d);g.x0=l/2;g.y0=0;F(g);B(g);e=G[b.orientation];v=new Searcher(()=>r,()=>l,y,{circle:()=>4.5,colour:z});k(g)});f=!0}function k(a){var d=A(g),
m=d.descendants();d=d.descendants().slice(1);m.forEach(function(h){h.y=h.depth*b.levelWidth});var t=u.selectAll("g.node").data(m,function(h){return h.id||(h.id=++J)}),n=t.enter().append("g").attr("class","node").attr("transform",function(h){return"translate("+e.x0(a)+","+e.y0(a)+")"}).on("click",K).on("mouseover",w.show).on("mouseout",w.hide).on("mousedown",function(h){w.hide();d3.event.stopPropagation()}).on("contextmenu",d3.contextMenu(C));n.append("circle").attr("r",1E-6).style("fill",z);n.append("text").attr("dy",
".35em");n=n.merge(t);n.select("text").attr("x",e.textOffsetXattr).attr("y",e.textOffsetYattr).attr("text-anchor",e.textAnchorAttr).text(p.textGetter).style("fill-opacity",1);n.transition().duration(b.duration).attr("transform",function(h){return"translate("+e.x(h)+","+e.y(h)+")"});n.select("circle").attr("r",4.5).style("fill",z).style("stroke",z).attr("cursor","pointer");t=t.exit().transition().duration(b.duration).attr("transform",function(h){return"translate("+e.x(a)+","+e.y(a)+")"}).remove();
t.select("circle").attr("r",1E-6);t.select("text").style("fill-opacity",1E-6);d=u.selectAll("path.link").data(d,function(h){return h.id});d.enter().insert("path","g").attr("class","link").attr("d",function(h){h={x:a.x0,y:a.y0};return e.link(h,h)}).merge(d).transition().duration(b.duration).attr("d",function(h){return e.link(h,h.parent)});d.exit().transition().duration(b.duration).attr("d",function(h){h={x:a.x,y:a.y};return e.link(h,h)}).remove();m.forEach(function(h){h.x0=h.x;h.y0=h.y});window.java&&
java.jsToJavaVisLoaded("visualisations.number_of_nodes.label",m.length.toString())}function D(){r=document.documentElement.clientWidth||window.innerWidth;l=document.documentElement.clientHeight||window.innerHeight;d3.select("svg").attr("width",r).attr("height",l)}function H(a,d){return"M"+e.x(a)+","+e.y(a)+"C"+(e.x(a)+e.x(d))/2+","+e.y(a)+" "+(e.x(a)+e.x(d))/2+","+e.y(d)+" "+e.x(d)+","+e.y(d)}function I(a,d){return"M"+e.x(a)+","+e.y(a)+"C"+e.x(a)+","+(e.y(a)+e.y(d))/2+" "+e.x(d)+","+(e.y(a)+e.y(d))/2+" "+e.x(d)+","+e.y(d)}function K(a){d3.event.shiftKey&&window.java?
java.jsToJavaNodeFocus(p.focussedNodeName(a)):a.children=a.children?null:a._children;k(a)}function q(a){return a.children||a._children}function F(a){a.children&&(a._children=a.children,a.children.forEach(F))}function B(a){q(a)&&(a._children.forEach(B),a.children=a.depth>=b.expandToLevel?null:a._children)}function z(a){a=b.useRegExNodeColour&&E&&E.test(a.data.display_url)?b.regExNodeColour:a.data.has_truncated_children&&a.depth<b.expandToLevel?0:a._children&&!a.children?b.collapsedNodeColour:b.useSegmentColour&&
a.data.segment_colour?cssHelpers.rgbIntToCssHex(a.data.segment_colour):b.useResponseCodeNodeColour?2==Math.floor(a.data.response_code/100)?cssHelpers.rgbIntToCssHex(b.nodeColour2xx):3==Math.floor(a.data.response_code/100)?cssHelpers.rgbIntToCssHex(b.nodeColour3xx):4==Math.floor(a.data.response_code/100)?cssHelpers.rgbIntToCssHex(b.nodeColour4xx):5==Math.floor(a.data.response_code/100)?cssHelpers.rgbIntToCssHex(b.nodeColour5xx):0==a.data.response_code?cssHelpers.rgbIntToCssHex(b.nodeColourNoResponse):
"#"+b.nodeColour:b.showNonIndexable&&treeVisHelpers.isNonIndexable(a)?b.nonIndexableNodeColour:b.useLeafNodeColour&&treeVisHelpers.isLeaf(a)?b.leafNodeColour:b.nodeColour;return cssHelpers.rgbIntToCssHex(a)}const G={"top-to-bottom":{x:function(a){return a.x},y:function(a){return a.y},x0:function(a){return a.x0},y0:function(a){return a.y0},link:function(a,d){return I(a,d)},textAnchorAttr:"middle",textOffsetXattr:a=>0,textOffsetYattr:a=>q(a)?-13:13},"right-to-left":{x:function(a){return r-a.y},y:function(a){return a.x},
x0:function(a){return r-a.y0},y0:function(a){return a.x0},link:function(a,d){return H(a,d)},textAnchorAttr:a=>q(a)?"start":"end",textOffsetXattr:a=>q(a)?13:-13,textOffsetYattr:a=>0},"bottom-to-top":{x:function(a){return a.x},y:function(a){return l-a.y},x0:function(a){return a.x0},y0:function(a){return l-a.y0},link:function(a,d){return I(a,d)},textAnchorAttr:"middle",textOffsetXAttr:a=>0,textOffsetYattr:a=>q(a)?13:-13},"left-to-right":{x:function(a){return a.y},y:function(a){return a.x},x0:function(a){return a.y0},
y0:function(a){return a.x0},link:function(a,d){return H(a,d)},textAnchorAttr:a=>q(a)?"end":"start",textOffsetXattr:a=>q(a)?-13:13,textOffsetYattr:a=>0}};let b={nodeLabel:"lastUrlPathComponent",duration:750,levelWidth:180,orientation:"left-to-right",textSizePx:12,nodeSpacing:50,visDataType:"CRAWL_MAP",expandToLevel:Math.MAX_SAFE_INTEGER,backgroundColour:16777215,textColour:0,linkColour:9474192,textDisplayDepth:9999,font:"impact",fontWeight:"normal",fontStyle:"normal",showNonIndexable:!0,useLeafNodeColour:!1,
nodeColour:4550936,useResponseCodeNodeColour:!1,useSegmentColour:!1,nodeColour2xx:4550936,nodeColour3xx:4550936,nodeColour4xx:4550936,nodeColour5xx:4550936,nodeColourNoResponse:4550936,leafNodeColour:0,nonIndexableNodeColour:13184301,collapsedNodeColour:12311902,truncatedNodeColour:0,useRegExNodeColour:!1,regExNodeColour:2774453,nodeColourRegExString:""},x,u,y,A,g,J=0,r=0,l=0,e,f=!1,p,v,E;(function(){D();d3.select(window).on("resize",function(){D()})})();let w,C;c.run=function(a){D();treeVisHelpers.clearPlaceholder();
p=strategyFactory(b,b.visDataType);if(!w){let d=d3.tip().attr("class","d3-tip").offset([-8,0]).html(p.toolTipHtml);d3.select("svg g").call(d);w=d}C||(C=p.rightClickMenu);d3.selection().datum(a).call(this);c.nodeColour(b.nodeColour);c.backgroundColour(b.backgroundColour);c.textColour(b.textColour);c.textSizePx(b.textSizePx);c.linkColour(b.linkColour)};c.search=function(a){return v.search(a)};c.searchNext=function(a){return v.searchNext(a)};c.searchPrev=function(a){return v.searchPrev(a)};c.centerSearchNode=
function(){v.centerOnNode()};c.enableConfig=function(a){f=a};c.visDataType=function(a){if(!arguments.length)return b.visDataType;b.visDataType=a;return this};c.save=function(){treeVisHelpers.chartSave(u)};c.configuration=function(a){if(!arguments.length)return b;let d=f;f=!1;for(var m in a)c[m](a[m]);f=d};c.orientation=function(a){if(!arguments.length)return b.orientation;b.orientation=a;f&&(e=G[b.orientation],k(g));return this};c.nodeSpacing=function(a){if(!arguments.length)return b.nodeSpacing;
b.nodeSpacing=a;f&&(A.nodeSize([b.nodeSpacing,b.nodeSpacing]),k(g));return this};c.textSizePx=function(a){if(!arguments.length)return b.textSizePx;b.textSizePx=a;f&&cssHelpers.setCssRule(".node text","fontSize",b.textSizePx+"px");return this};c.textDisplayDepth=function(a){if(!arguments.length)return b.textDisplayDepth;b.textDisplayDepth=a;f&&k(g);return this};c.duration=function(a){if(!arguments.length)return b.duration;b.duration=a;return this};c.levelWidth=function(a){if(!arguments.length)return b.levelWidth;
b.levelWidth=a;f&&k(g);return this};c.backgroundColour=function(a){if(!arguments.length)return b.backgroundColour;b.backgroundColour=a;f&&(cssHelpers.setCssRule(".svg","backgroundColor",cssHelpers.rgbIntToCssHex(b.backgroundColour)),k(g));return this};c.textColour=function(a){if(!arguments.length)return b.textColour;b.textColour=a;f&&cssHelpers.setCssRule(".node text","fill",cssHelpers.rgbIntToCssHex(b.textColour));return this};c.linkColour=function(a){if(!arguments.length)return b.linkColour;b.linkColour=
a;f&&cssHelpers.setCssRule("path","stroke",cssHelpers.rgbIntToCssHex(b.linkColour));return this};c.expandToLevel=function(a){if(!arguments.length)return b.expandToLevel;b.expandToLevel=a;f&&(B(g),k(g));return this};c.clear=function(a){d3.selectAll("svg g path").remove();d3.selectAll("svg g g").remove();treeVisHelpers.setPlaceholder(a)};c.showNonIndexable=function(a){if(!arguments.length)return b.showNonIndexable;b.showNonIndexable=a;return this};c.nodeColour=function(a){if(!arguments.length)return b.nodeColour;
b.nodeColour=a;f&&k(g);return this};c.leafNodeColour=function(a){if(!arguments.length)return b.leafNodeColour;b.leafNodeColour=cssHelpers.rgbIntToCssHex(a);f&&k(g);return this};c.useLeafNodeColour=function(a){if(!arguments.length)return b.useLeafNodeColour;b.useLeafNodeColour=a;f&&k(g);return this};c.nonIndexableNodeColour=function(a){if(!arguments.length)return b.nonIndexableNodeColour;b.nonIndexableNodeColour=cssHelpers.rgbIntToCssHex(a);f&&k(g);return this};c.nodeLabel=function(a){if(!arguments.length)return b.nodeLabel;
b.nodeLabel=a;f&&(p.setNodeLabel(b.nodeLabel),d3.selectAll("text").text(p.textGetter));return this};c.collapsedNodeColour=function(a){if(!arguments.length)return b.collapsedNodeColour;b.collapsedNodeColour=cssHelpers.rgbIntToCssHex(a);f&&k(g);return this};c.truncatedNodeColour=function(a){if(!arguments.length)return b.truncatedNodeColour;b.truncatedNodeColour=cssHelpers.rgbIntToCssHex(a);return this};c.font=function(a){if(!arguments.length)return b.font;b.font=a;cssHelpers.setCssRule(".node text",
"font-family",b.font+",sans-serif");return this};c.fontWeight=function(a){if(!arguments.length)return b.fontWeight;b.fontWeight=a;cssHelpers.setCssRule(".node text","font-weight",b.fontWeight);return this};c.fontStyle=function(a){if(!arguments.length)return b.fontStyle;b.fontStyle=a;cssHelpers.setCssRule(".node text","font-style",b.fontStyle);return this};c.useRegExNodeColour=function(a){if(!arguments.length)return b.useRegExNodeColour;b.useRegExNodeColour=a;f&&k(g);return this};c.nodeColourRegExString=
function(a){if(!arguments.length)return b.nodeColourRegExString;b.nodeColourRegExString=a;E=b.nodeColourRegExString?new RegExp(b.nodeColourRegExString):null;f&&k(g);return this};c.regExNodeColour=function(a){if(!arguments.length)return b.regExNodeColour;b.regExNodeColour=a;f&&k(g);return this};c.useResponseCodeNodeColour=function(a){if(!arguments.length)return b.useResponseCodeNodeColour;b.useResponseCodeNodeColour=a;f&&k(g);return this};c.useSegmentColour=function(a){if(!arguments.length)return b.useSegmentColour;
b.useSegmentColour=a;f&&k(g);return this};c.nodeColour2xx=function(a){if(!arguments.length)return b.nodeColour2xx;b.nodeColour2xx=a;f&&k(g);return this};c.nodeColour3xx=function(a){if(!arguments.length)return b.nodeColour3xx;b.nodeColour3xx=a;f&&k(g);return this};c.nodeColour4xx=function(a){if(!arguments.length)return b.nodeColour4xx;b.nodeColour4xx=a;f&&k(g);return this};c.nodeColour5xx=function(a){if(!arguments.length)return b.nodeColour5xx;b.nodeColour5xx=a;f&&k(g);return this};c.nodeColourNoResponse=
function(a){if(!arguments.length)return b.nodeColourNoResponse;b.nodeColourNoResponse=a;f&&k(g);return this};return c}let chart=treeChart();
